version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - npm install
  build:
    commands:
      - echo "Build started on `date`"
      - npm run build
      - mkdir output
      - cp -r build/* output/  # Copy the contents of the build folder to the output directory
  post_build:
    commands:
      - echo "Build completed on `date`"

artifacts:
  files:
    - '**/*'
  base-directory: output  # Use the "output" directory as the artifact source
  discard-paths: no
